### ISSUE TITLE
[Feature request]: App description in F-Droid and README is subpar

### ISSUE THREAD

**Issue by vi** [LinwoodCloud/butterfly#25]
### What happened?

README and F-Droid page starts with "Change the world", which is rather vague. Changelog suggests that it is somehow graphics related. "The data is saves in json fils" suggests that this graphics is vector graphics.

#16 even expected it to be some notes app.

There are a lot of notes and simple raster draw apps for Android, but vector graphics editors (even simple ones) are rare, especially open source ones.

I suggest to fix app description to position Butterfly as vector graphics editor for web and Android explicitly.

P.S.

> "The paper has an infinite size, ..."

With zoom levels capped between 25% and 500%, this infinity is rather finite.

### Version

2.0.0-rc.0 (Latest snapshot)

### Platform

Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
I think we can close this when we let #16 opened. The size is infinite because you can move infinite on left, top, bottom and right. I want to positioned the app as drawing app because you cannot export it as svg in the current time and have currently no option to have shapes which are very important if you need a vector app. You are right technically, it doesn't save pixels.

**Comment by CodeDoctorDE** [comment]
By the way: Change the world should be the slogan of the app. `Simple note app` is for me too boring

**Comment by CodeDoctorDE** [comment]
We can discuss the description in #16 :)

**Comment by vi** [comment]
> Simple note app is for me too boring

It is indeed boring and I think the emphasis should be on vector graphics, not on notes.
"Simple vector graphics app" is already less boring (due to scarcity of such apps).
